model: 
  sde: VP
  beta_min: 0.1
  beta_max: 20.
  num_scales: 1000
  sampling_eps: 0.001
  ckpt: 'exp/mnist-train/ckpts/model-200.pt'

train:
  batchsize: 128
  num_epoch: 201
  continuous: True
  save_step: 25
  eval_step: 25

optim:
  lr: 0.0005
  warmup: 5000
  grad_clip: 1.

sampling:
  method: 'pc'
  predictor: 'euler_maruyama'
  corrector: 'none'
  snr: 0.16
  n_steps_each: 1
  noise_removal: True
  probability_flow: True
  eps: 0.001
  num_samples: 16


log:
  basedir: mnist-train